### ISSUE TITLE
First canvas checklist

### ISSUE THREAD

**Issue by Hans5958** [placeAtlas/atlas-2023#1]
This checlist describes what needs to be done to start the Atlas with the first canvas (variation/version). This is done on 30 minutes after the start of the event.

`config.js` is located on `web/_js/config.js`.

- [ ] Configure the size of the canvas on `config.js`
   ```js
   const canvasSize = {
    	x: 2000,
	   y: 2000
   }
   ```
- [ ] Update timestamp of the start version to the real starting time on `config.js`
   Example:
   ```json
			{ "timestamp": 1490981400, "url": ["./_img/canvas/main-ex/start.png"] },
   ```
- [ ] Add image to `web/_img/canvas/main`
   Recommended name: `[unix timestamp in seconds].png`
   Doesn't have to be accurate. Doesn't need to be converted into deltas.
   If it is done in 1 hour and up, add the available images in 30-minute intervals since the start of the event.
- [ ] Add added image version to the `config.js`
   If it is done in 1 hour and up, add the available images in 30-minute intervals since the start of the event.
   Example:
   ```json5
   {
      // ...
   		versions: [
			{ "timestamp": 1490981400, "url": ["./_img/canvas/main-ex/start.png"] },
			{ "timestamp": 1490983200, "url": ["./_img/canvas/main/1490983200.png"] },
		],
	// ....
	}
```
- [ ] Announce that submmisions are accepted

**Comment by Hans5958** [comment]
Discord message to post regarding the overview.

- The Atlas will be available in https://2023.place-atlas.stefanocoding.me. The design will be similar to the 2022 Atlas, so you can make yourself familiar before the real deal.
- The Atlas will be available as soon as the first canvas is available. That would be at least 30 minutes after the start of the event.
- Submissions will open as soon as soon as the Atlas available. You can start submitting at that time.
- We will watch these places for submissions. Automated submissions would be submissions that are generated using the website. Manual requests are also accepted, but please be patient until one of us can handle it. 
   - GitHub: The placeAtlas/atlas-2023 repository (https://github.com/placeAtlas/atlas-2023/pulls)
      This is the **recommended** method for automated submissions. If you haven't, please create a GitHub account.
   - Reddit: The r/placeAtlas2023 subreddit for submissions 
      This is also for automated submissions, but due to the limitations to the API, this may be slower. Use GitHub for a faster response.
   - Discord: The #atlas-edits forum
      This is primarily for manual requests for edits.
- The canvases would be updated as the event goes on. Please be patient while we're trying to keep it updated. Other variations, such as TFC, would be added later.
- Before posting a submissions, it is better to check these.
   - If the entry already exists in the Atlas.
   - If the submission already exists for your change. This includes additions that are not in the atlas, but is queued to be published. The recommended places to check is the patches folder on the repository (https://github.com/placeAtlas/atlas-2023/tree/master/data/patches) and the latest pull requests, open and closed (https://github.com/placeAtlas/atlas-2023/pulls)
   - If the entry already exists in the Atlas **in the past**. Also check the two or three images back, as an entry may reappearing.
- Do not rush! We don't want low quality submissions. If needed, you can continue the work after a submission/added entry.
